[[applications]]
application = "Projectionist"
date = 2460093
version = "1.0.1"

[[apps]]
AppAlias = "Awk"
AppReal = "awk"
AppVerGet = "-W version"
RegexStart = 5
RegexEnd = 10
Type = "Tool"

[[apps]]
AppAlias = "Bash"
AppReal = "bash"
AppVerGet = "--version"
RegexStart = 17
RegexEnd = 23
Type = "Tool"

[[apps]]
AppAlias = "CMake"
AppReal = "cmake"
AppVerGet = "--version"
RegexStart = 14
RegexEnd = 20
Type = "Tool"

[[apps]]
AppAlias = "Dia"
AppReal = "dia"
AppVerGet = "-v"
RegexStart = 12
RegexEnd = 18
Type = "Tool"

[[apps]]
AppAlias = "Dot"
AppReal = "dot"
AppVerGet = "-V"
RegexStart = 22
RegexEnd = 29
Type = "Tool"

[[apps]]
AppAlias = "Doxygen"
AppReal = "doxygen"
AppVerGet = "--version"
RegexStart = 0
RegexEnd = 5
Type = "Tool"

[[apps]]
AppAlias = "GDB"
AppReal = "gdb"
AppVerGet = "--version"
RegexStart = 31
RegexEnd = 35
Type = "Tool"

[[apps]]
AppAlias = "Git"
AppReal = "git"
AppVerGet = "-v"
RegexStart = 12
RegexEnd = 20
Type = "Tool"

[[apps]]
AppAlias = "GMake"
AppReal = "gmake"
AppVerGet = "--version"
RegexStart = 8
RegexEnd = 12
Type = "Tool"

[[apps]]
AppAlias = "Jq"
AppReal = "jq"
AppVerGet = "--version"
RegexStart = 3
RegexEnd = 6
Type = "Tool"

[[apps]]
AppAlias = "Ninja"
AppReal = "ninja"
AppVerGet = "--version"
RegexStart = 0
RegexEnd = 6
Type = "Tool"

[[apps]]
AppAlias = "Pip3"
AppReal = "pip3"
AppVerGet = "--version"
RegexStart = 4
RegexEnd = 10
Type = "Tool"

[[apps]]
AppAlias = "Python3"
AppReal = "python3"
AppVerGet = "--version"
RegexStart = 7
RegexEnd = 13
Type = "Tool"

[[apps]]
AppAlias = "Qt Designer"
AppReal = "qtdesignstudio"
AppVerGet = "--version"
RegexStart = 35
RegexEnd = 41
Type = "Application"

[[apps]]
AppAlias = "Qt Creator"
AppReal = "qtcreator"
AppVerGet = "--version"
RegexStart = 11
RegexEnd = 16
Type = "Application"

[[apps]]
AppAlias = "Qt"
AppReal = "qtdesignstudio"
AppVerGet = "--version"
RegexStart = 17
RegexEnd = 23
Type = "Tool"

[[apps]]
AppAlias = "Sed"
AppReal = "sed"
AppVerGet = "--version"
RegexStart = 23
RegexEnd = 26
Type = "Tool"

[[apps]]
AppAlias = "VSCode"
AppReal = "code"
AppVerGet = "--version"
RegexStart = 0
RegexEnd = 6
Type = "Application"

[[apps]]
AppAlias = "Whoami"
AppReal = "whoami"
AppVerGet = "--version"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Whereis"
AppReal = "whereis"
AppVerGet = "-V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Find"
AppReal = "find"
AppVerGet = "--version"
RegexStart = 21
RegexEnd = 25
Type = "Tool"

[[apps]]
AppAlias = "PyCharm"
AppReal = "pycharm"
AppVerGet = "--version"
RegexStart = 123
RegexEnd = 128
Type = "Application"

[[apps]]
AppAlias = "PhpStorm"
AppReal = "phpstorm"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Application"

[[apps]]
AppAlias = "UltraEdit"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Application"

[[apps]]
AppAlias = "UltraCompare"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Application"

[[apps]]
AppAlias = "Krita"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Application"

[[apps]]
AppAlias = "Gimp"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Application"

[[apps]]
AppAlias = "Powershell"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Sudo"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "List"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Copy"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Remove"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Move"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Make Directory"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Disk Free"
AppReal = "df"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Disk Usage"
AppReal = "du"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Cat"
AppReal = "cat"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Grep"
AppReal = "grep"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Git Hub"
AppReal = "gh"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Tool"

[[apps]]
AppAlias = "Arduino IDE"
AppReal = "whereis"
AppVerGet = "V"
RegexStart = 23
RegexEnd = 27
Type = "Application"
