"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from shiboken6 import Shiboken

class Object:
    def __init__(self) -> None:
        ...
    


class VoidPtr:
    ...


def createdByPython(arg__1: Shiboken.Object) -> bool:
    ...

def delete(arg__1: Shiboken.Object) -> None:
    ...

def dump(arg__1: object) -> str:
    ...

def getAllValidWrappers() -> list[Shiboken.Object]:
    ...

def getCppPointer(arg__1: Shiboken.Object) -> tuple[int, ...]:
    ...

def invalidate(arg__1: Shiboken.Object) -> None:
    ...

def isValid(arg__1: object) -> bool:
    ...

def ownedByPython(arg__1: Shiboken.Object) -> bool:
    ...

def wrapInstance(arg__1: int, arg__2: type) -> Shiboken.Object:
    ...

